on:
  push:
    branches:
      - 'feat/github-action-push-to-supabase'
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * 0'

jobs:
  pumps-staging:
    runs-on: ubuntu-latest
    environment: staging
    uses: ./.github/workflows/pumps.yml
    with:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_DATA_ASSETS_BUCKET: ${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}
      SUPABASE_ACCESS_TOKEN: ${{ vars.SUPABASE_ACCESS_TOKEN }}