on:
  push:
    branches:
      - 'feat/github-action-push-to-supabase'
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * 0'

jobs:
  pumps-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: ./.github/workflows/pumps.yml