on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * 0'

jobs:
  pumps-staging:
    environment: staging
    uses: ./.github/workflows/pumps.yml
    with:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_DATA_ASSETS_BUCKET: ${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}